prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_FE

README.md
> closes #3 
> social preview 이미지 추가
=> [merge / 3-feat-add-logo-image-to-readmemd]✨feat: README.md 파일에 미리보기 이미지 추가

package.json, yarn.lock
=> [merge / 5-feat-initialize-project-file] 🎨 add: zustand, tanstack query 설치

src/app/(with-title)/join/page.tsx, src/app/(with-title)/layout.tsx, src/app/(with-title)/login/page.tsx, src/app/admin/feedback/page.tsx, src/app/admin/layout.tsx, src/app/admin/page.tsx, src/app/admin/postits/page.tsx, src/app/admin/reports/page.tsx, src/app/admin/terms/page.tsx, src/app/admin/users/page.tsx, src/app/directions/page.tsx, src/app/feedback/[id]/edit/page.tsx, src/app/feedback/[id]/page.tsx, src/app/feedback/page.tsx, src/app/feedback/write/page.tsx, src/app/my-page/my-postits/page.tsx, src/app/my-page/page.tsx, src/app/my-page/profile/page.tsx, src/app/my-page/settings/page.tsx, src/app/my-place/edit/page.tsx, src/app/my-place/layout.tsx, src/app/my-place/page.tsx
> #11 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
페이지 라우팅 작업을 하였습니다.
초기 레이아웃을 설정했습니다.
=> [merge / 11-feat-initial-routing] ✨ feat: 페이지 라우팅

src/auth.ts, src/types/next-auth.d.ts
> #57
> Next Auth Session에 user 정보 담기
=> [merge / 57-feat-next-auth-featured] ✨ Feat. user 정보

src/app/(user)/(service)/my-place/edit/page.tsx, src/app/(user)/(service)/my-place/page.tsx, src/components/common/nav/Navbar.tsx, src/components/my-place/MyPlaceItem.tsx, src/components/my-place/MyPlaceList.tsx, src/components/my-place/MyPlaceListEdit.tsx, src/types/my-place.d.ts
> #
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 즐겨찾기 리스트 API 연결
- 즐겨찾기 삭제 API 연결
- 즐겨찾기 순서 수정 API 연결
=> [merge / 63 feat my place]  ✨ Feat. 즐겨찾기 화면 리스트, 삭제, 순서 수정 API 연결

src/components/auth/join-form/join-form.tsx, src/components/auth/login/login-form.tsx, src/components/auth/password-input.tsx, src/components/auth/reset-password/reset-password.tsx, src/components/common/form/CheckboxGroup.tsx, src/components/my-page/ProfileEdit.tsx
=> [merge / fix-build-any-types ]🚨Fix. any 타입 수정

src/firebase/firebase.ts
=> [merge / 72-feat-implement-fcm-push-message] 🚨 fix: FCM 모바일 테스트코드 추가

src/app/api/feedback/fetchCommentList.ts, src/components/feedback/FeedbackComment.tsx, src/components/feedback/FeedbackCommentList.tsx, src/types/feedback/feedbackList.d.ts
=> [merge / 84-feat-feedback-page-delete-comment]✨ feat: 피드백 화면 댓글 삭제 버튼 기능 구현

src/app/(user)/(service)/page.tsx, src/components/home/A2HS.tsx
> #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 🚨 fix: 랜딩페이지 레이아웃 수정 및 코드 병합

src/auth.ts
=> [merge / fix-token ]🚨Fix. 토큰 에러

src/app/manifest.ts, src/components/home/A2HS.tsx
> #100 
> A2HS UI수정 및 manifest 파일 수정
=> [merge / 100-feat-modify-a2hs-ui] ✨ feat: A2HS UI수정 및 manifest 파일 수정

src/app/layout.tsx, src/app/manifest.ts, src/components/home/A2HS.tsx, src/components/home/ThemeColorUpdater.tsx
> #104 
> manifest 파일 theme_color 적용
=> [merge / 104-bug-fix-manifest-theme-color-settings] 🚨 fix: 코드 병합

src/app/layout.tsx, src/app/manifest.ts, src/components/home/A2HS.tsx, src/components/home/ThemeColorUpdater.tsx
manifest theme_color 적용 테스트 배포
=> Signal_Buddy_pre_release_1.2.3

src/app/(user)/(service)/feedback/[id]/edit/page.tsx
=> [merge / 113-hotfix-build-error]🚨 fix: 코드 변경사항 반영

src/app/(user)/(service)/feedback/[id]/page.tsx, src/components/fcm/FCMNotification.tsx, src/firebase/firebase.ts
> #116
> 푸시알림 토큰 등록 api 설정
> 푸시알림 서버로부터 url 넘겨받아야 링크 리다이렉션 가능
=> [merge / 116-feat-fcm-pushmassage-api]✨ feat: 푸시알림 링크 설정

src/app/(user)/(service)/feedback/[id]/edit/page.tsx, src/app/(user)/(service)/feedback/[id]/page.tsx, src/components/fcm/FCMNotification.tsx, src/firebase/firebase.ts
=>  Signal_Buddy_pre_release_1.2.6

src/app/(user)/(service)/feedback/[id]/page.tsx, src/app/(user)/(service)/my-page/settings/page.tsx, src/components/auth/login/login-form.tsx, src/components/feedback/FeedbackSearchbar.tsx
> #119 
> 피드백 검색기능 개선
> 검색기능 api 완결성 검토 필요
=> [merge / 119-feat-modify-feedback-search-bar] ✨ feat: 검색기능 개선

components/ui/pagination.tsx, src/app/(user)/(service)/feedback/[id]/page.tsx, src/app/(user)/(service)/feedback/page.tsx, src/app/api/feedback/fetchFeedbackList.ts, src/app/api/feedback/likeButton.ts, src/components/feedback/ui/FeedbackPagination.tsx, src/components/shadcn/components/ui/pagination.tsx
> #121 
> 피드백 리스트 페이지네이션 기능 구현
=> [merge / 121-feat-feedback-pagenation] ✨ feat: 피드백 리스트 페이지네이션 기능 추가

src/components/fcm/FCMNotification.tsx
> #129 
> 피드백 아이디 수신하여 fcm링크 리디렉션 적용
=> [merge / 129-feat-fcm-link-handling]✨ feat: fcm link 연결

src/components/fcm/FCMNotification.tsx
=> [merge / 129-feat-fcm-link-handling] 🚨 fix: fcm link error

src/components/fcm/FCMNotification.tsx
=> Signal_Buddy_pre_release_1.2.10

src/auth.ts, src/components/map/MapBox.tsx, src/components/map/MapButtons.tsx, src/components/map/crossroads/MapCrossRoad.tsx, src/components/map/direction/MapDirection.tsx, src/hooks/useGeoLocation.ts, src/hooks/useMapCrossRoad.ts, src/lib/api/client/index.ts, src/types/next-auth.d.ts
=> [merge / 123 bug first qa fix] 🚨 1차 qa

src/app/(user)/(service)/feedback/[id]/page.tsx, src/app/(user)/(service)/feedback/write/page.tsx, src/components/common/footer/Footer.tsx, src/components/feedback/FeedbackEditPost.tsx, src/components/feedback/ui/CrossRoadSearchbar.tsx, src/utils/formatFeedbackCategory.ts
=> [merge / 134-feat-feedback-write-connect-map-info]🔨 chore: 코드 병합

src/app/(user)/(service)/feedback/write/page.tsx, src/hooks/useSearchParamsClient.ts
=> [merge / 134-feat-feedback-write-connect-map-info]🚨 fix: useParams suspense error 수정

src/app/(user)/(service)/feedback/[id]/page.tsx, src/app/api/feedback/likeButton.ts
=> [merge / 147-bug-feedback-token-error]🚨 fix: 피드백 토큰 에러 처리

src/app/(user)/(service)/feedback/[id]/page.tsx, src/app/api/feedback/fetchFeedbackItem.ts, src/app/api/feedback/likeButton.ts, src/components/common/profile/Profile.tsx, src/components/feedback/FeedbackComment.tsx, src/components/feedback/FeedbackCommentList.tsx, src/components/feedback/FeedbackLikeButton.tsx, src/components/feedback/FeedbackList.tsx, src/components/feedback/LikeBTN.tsx, src/firebase/firebase.ts
> #149 
> 피드백 화면 아바타 컴포넌트 적용
> 피드백 댓글 영역 ui 조정
> 좋아요 버튼 기능 오류 해결 및 코드 단순화
=> [merge / 149-feat-feedback-adapt-avatar] ✨ feat: 피드백 화면 아바타 컴포넌트 적용

src/app/(user)/(service)/feedback/page.tsx, src/app/globals.css, src/components/feedback/ui/FeedbackPagination.tsx
> #153 
> 페이지네이션 검새 결과에 따라 동적으로 바뀌도록 개선
=> [merge / 153-bug-feedback-filtering-pagination-error] 🚨 fix: pagination optimization

src/app/(user)/(service)/my-page/liked/page.tsx, src/app/(user)/(service)/my-page/settings/page.tsx, src/app/(user)/(service)/my-place/edit/page.tsx, src/app/(user)/(service)/my-place/page.tsx, src/app/(user)/(service)/page.tsx, src/components/my-page/RecentDestinations.tsx, src/components/my-place/MyPlaceDialog.tsx, src/components/my-place/MyPlaceList.tsx, src/components/my-place/MyPlaceListEdit.tsx, src/components/my-place/MyPlacePagination.tsx
> #139 
> 즐겨찾기 페이지네이션 구현
> 즐겨찾기 수정 기능
> 메인 화면 이미지 변경
> 회원 탈퇴 확인 모달
> 마이페이지 내가 좋아한 피드백 스타일 수정 및 페이지네이션
=> [merge / 139 feat my place]  pagination

package.json, src/app/api/tts/route.ts, src/components/map/direction/MapDirection.tsx, yarn.lock
=> [merge/154-bug-tts-voice] 🚨Fix. TTS 적용

src/app/not-found.tsx
=> [merge/ feat-not-found-page]✨Feat. 404 Page

src/app/(user)/(service)/my-page/liked/page.tsx, src/app/(user)/(service)/my-page/settings/page.tsx, src/components/my-page/LikedFeedbackList.tsx, src/components/my-page/RecentDestinations.tsx, src/components/my-page/RecentDestinationsItem.tsx, src/components/my-place/MyPlaceList.tsx, src/components/my-place/MyPlacePagination.tsx, tailwind.config.ts
> #158 
> 내가 좋아한 피드백 스타일 개선
> 페이지네이션 5개까지 보이게 수정
> 탈퇴 확인 모달 버튼 색 변경
> 최근 경로 hover 스타일 개선
=> [merge / 158 style my page feedback detail] 마이페이지 스타일 개선

src/app/(user)/(service)/feedback/write/page.tsx, src/components/feedback/FeedbackSearchbar.tsx, src/components/map/search/MapSearchResult.tsx, tailwind.config.ts
> #164 
> 다크모드 적용 안 된 것으로 확인된 부분이 있어 수정했습니다. (지도 장소 설명란)
=> [merge / 164-style-map-dark-mode] 💄 style: 다크모드 적용 안 된 부분 수정

src/app/(user)/(service)/my-page/settings/page.tsx, src/features/auth/auth-common/actions/index.ts, src/features/auth/auth-common/actions/logout.ts, src/features/auth/auth-common/components/logout-btn.tsx, src/features/auth/auth-join/actions/index.ts, src/features/auth/auth-join/actions/join-schema.ts, src/features/auth/auth-join/actions/join.ts, src/features/auth/auth-join/components/join-form.tsx, src/features/auth/auth-login/actions/index.ts, src/features/auth/auth-login/actions/login-schema.ts, src/features/auth/auth-login/actions/login.ts, src/features/auth/auth-login/components/login-form.tsx, src/features/auth/auth-login/components/social-login.tsx, src/features/auth/auth-reset-pw/actions/index.ts, src/features/auth/auth-reset-pw/actions/post-verify-code.ts, src/features/auth/auth-reset-pw/actions/reset-pw.ts, src/features/auth/auth-reset-pw/actions/reset-schema.ts, src/features/auth/auth-reset-pw/components/email-form.tsx, src/features/auth/auth-reset-pw/components/otp-form.tsx, src/features/auth/auth-reset-pw/components/reset-password-verification.tsx, src/features/auth/auth-reset-pw/components/reset-password.tsx, tailwind.config.ts
=> [MERGE/176-refactor-refactor-auth]🔨Refactor. Auth actions 분리

src/features/map/map-search/actions/index.ts, src/features/map/map-search/actions/save-recent-path.ts, src/features/map/map-search/components/map-search-result.tsx
=> [merge/182-refactor-map-code] 🔨Refactor. map actions

src/features/my-place/my-place-edit/index.tsx, src/hooks/use-my-place-edit.ts
> #188 
> 즐겨찾기 편집 후 페이지 변경 시 변경사항 반영되도록 수정
=> [merge/ 188-refactor-my-place-refactor ]🚨Fix: 페이지 바꿨을 때 변경사항 반영되도록 수정
